spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_reservations
    username: postgres
    password: genius2811
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true 